nav:
  - index.md
  - Dashing to Eloquent: Dashing.md
  - Eloquent to Foxy: Eloquent.md
  - Foxy to Galactic: foxy/Foxy.md
  - Galactic to Humble: galactic/Galactic.md
  - Humble to Iron: Humble.md
  - Iron to Jazzy: iron/Iron.md
  - Jazzy to Kilted: jazzy/Jazzy.md
  - Kilted to Lyrical: kilted/Kilted.md
  - Lyrical to M-Turtle: Lyrical.md
