site_name: Nav2
# site_url: https://docs.nav2.org/ # Uncomment after documentation release
repo_url: https://github.com/ros-navigation/navigation2
repo_name: ros-navigation/navigation2
# repo_url: https://github.com/ros-navigation/docs.nav2.org
# repo_name: ros-navigation/docs.nav2.org
copyright: © Copyright 2026, Open Navigation LLC.

theme:
  name: material
  logo: images/nav2_logo_48x48.png
  favicon: images/nav2_logo_48x48.png
  icon:
    repo: fontawesome/brands/github
  palette:
  # Palette for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  # Palette for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - content.code.copy

plugins:
  - search
  - mike # All parameters: https://github.com/jimporter/mike#configuration

extra:
  version:
    provider: mike
  scope: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ros-navigation/navigation2
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/navigation2/shared_invite/zt-uj428p0x-jKx8U7OzK1IOWp5TnDS2rA

extra_css: 
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

nav:
  - index.md
  - Getting Started: getting_started/index.md 