# Keep site_name empty; the header title displays alongside the logo
# The tab title is overridden in the htmltitle block of overrides/main.html
site_name: ""
# site_url: https://docs.nav2.org/ # Uncomment after documentation release
repo_url: https://github.com/ros-navigation/navigation2
repo_name: ros-navigation/navigation2
# repo_url: https://github.com/ros-navigation/docs.nav2.org
# repo_name: ros-navigation/docs.nav2.org
copyright: "&copy; Copyright 2026, Open Navigation LLC."

edit_uri: https://github.com/ros-navigation/mk.docs.nav2.org/blob/jazzy/docs/ # Update link after documentation release

theme:
  name: material
  custom_dir: overrides
  logo: images/nav2_logo_with_text.png
  favicon: images/nav2_logo_48x48.png
  font:
    text: Inter
  icon:
    repo: fontawesome/brands/github
  palette:
  # Palette for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  # Palette for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top # back-to-top button

plugins:
  - search
  - mike # All parameters: https://github.com/jimporter/mike#configuration
  - autorefs
  - glightbox
  - macros:
      module_name: macros/main
      include_yaml:
        - macros/variables.yml
      on_error_fail: true
      on_undefined: strict

extra:
  version:
    provider: mike
  scope: /
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ros-navigation/navigation2
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/navigation2/shared_invite/zt-uj428p0x-jKx8U7OzK1IOWp5TnDS2rA

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

  # Path relative to custom_dir (overrides/):
  - assets/stylesheets/extra.css
  - assets/stylesheets/search_button.css
  - assets/stylesheets/sidebar.css
  - assets/stylesheets/distro_grid.css
  - assets/stylesheets/robots_grid.css
  - assets/stylesheets/table.css
  - assets/stylesheets/nav_buttons.css
  - assets/stylesheets/permalink.css
  - assets/stylesheets/sponsorship_banner.css
  - assets/stylesheets/images.css

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

  # Path relative to custom_dir (overrides/):
  - assets/javascripts/katex.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: ''
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true

# Terminate the build on warning
strict: true

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
  nav:
    omitted_files: warn
    absolute_links: warn

exclude_docs: |
  axis_goal_checker_illustration.py
  adaptive_tolerance_goal_checker_illustration.py
  CancelCoverage.md
  ComputeCoveragePath.md
  2021summerOfCode

INHERIT: nav.yml
