nav:
  - index.md
  - Setup Guide for Gazebo:
    - gazebo/index.md
    - Setting Up Transformations: transformation/setup_transforms.md
    - Setting Up The URDF: urdf/setup_urdf.md
    - Setting Up The SDF - Gazebo: sdf/setup_sdf.md
    - Setting Up Odometry - Gazebo: odom/setup_odom_gz.md
    - Smoothing Odometry using Robot Localization: odom/setup_robot_localization.md
    - Setting Up Sensors - Gazebo: sensors/setup_sensors_gz.md
    - Mapping and Localization: sensors/mapping_localization.md
    - Setting Up the Robot's Footprint: footprint/setup_footprint.md
    - Setting Up Navigation Plugins: navigation_plugins/setup_navigation_plugins.md
  - Setup Guide for Gazebo Classic:
    - gazebo_classic/index.md
    - Setting Up Transformations: transformation/setup_transforms.md
    - Setting Up The URDF: urdf/setup_urdf.md
    - Setting Up Odometry - Gazebo Classic: odom/setup_odom_gz_classic.md
    - Smoothing Odometry using Robot Localization: odom/setup_robot_localization.md
    - Setting Up Sensors - Gazebo Classic: sensors/setup_sensors_gz_classic.md
    - Mapping and Localization: sensors/mapping_localization.md
    - Setting Up the Robot's Footprint: footprint/setup_footprint.md
    - Setting Up Navigation Plugins: navigation_plugins/setup_navigation_plugins.md
