version: 2.1

references:
  on_checkout: &on_checkout
    checkout:
      path: .
  setup_doc_dependencies: &setup_doc_dependencies
    run:
      name: Install documentation dependencies
      command: |
        export DEBIAN_FRONTEND=noninteractive
        apt update
        apt install -y \
          git \
          openssh-server \
          python3-pip \
          python3-venv
        python3 -m venv /nav2_docs/venv
        . /nav2_docs/venv/bin/activate
        pip3 install -r requirements.txt
  build_docs: &build_docs
    run:
      name: Build documentation
      command: |
        . /nav2_docs/venv/bin/activate
        mkdocs build
  store_built_docs: &store_built_docs
    store_artifacts:
      path: ./site
      destination: build_site
  publish_docs: &publish_docs
    run:
      name: Deploy documentation
      command: |
        # Set up git configuration
        git config user.name ci
        git config user.email ci@noreply.com

        . /nav2_docs/venv/bin/activate

        TITLE=${CIRCLE_BRANCH^}
        mike deploy $CIRCLE_BRANCH --title=$TITLE --push --allow-empty \
          --message "[skip ci] Deployed $CIRCLE_SHA1 to $CIRCLE_BRANCH"

        # Set default version only once
        if ! git cat-file -e origin/gh-pages:index.html; then
          mike set-default rolling --push
          echo "The default version is set to Rolling"
        fi
  store_published_docs: &store_published_docs
    store_artifacts:
      path: ./site
      destination: publish_site
  install_deployment_key: &install_deployment_key
    add_ssh_keys:
      fingerprints:
        - "SHA256:ZnRqrDobYvOKwaOK93Ro6i0MI7sITLQlf4DGjX+mYcE"

commands:
  install_doc_dependencies:
    description: "Install documentation dependencies"
    steps:
      - *setup_doc_dependencies
  build_and_store_docs:
    description: "Build and store docs"
    steps:
      - *build_docs
      - *store_built_docs
  publish_and_store_docs:
    description: "Commit newly built docs to gh-pages branch and store the build result"
    steps:
      - *publish_docs
      - *store_published_docs

executors:
  docs_exec:
    docker:
      - image: ubuntu:noble
    working_directory: /nav2_docs

jobs:
  docs_build:
    executor: docs_exec
    steps:
      - *on_checkout
      - install_doc_dependencies
      - build_and_store_docs
  docs_publish:
    executor: docs_exec
    steps:
      - *on_checkout
      - install_doc_dependencies
      - *install_deployment_key
      - publish_and_store_docs

workflows:
  build_docs:
    jobs:
      - docs_build:
          filters:
            branches:
              ignore:
                - rolling
  publish_docs:
    jobs:
      - docs_publish:
          filters:
            branches:
              only:
                - rolling
