nav:
  - index.md
  - Action Plugins:
    - Wait: actions/Wait.md
    - Spin: actions/Spin.md
    - BackUp: actions/BackUp.md
    - DriveOnHeading: actions/DriveOnHeading.md
    - AssistedTeleop: actions/AssistedTeleop.md
    - ComputePathToPose: actions/ComputePathToPose.md
    - ComputeRoute: actions/ComputeRoute.md
    - ComputeAndTrackRoute: actions/ComputeAndTrackRoute.md
    - FollowPath: actions/FollowPath.md
    - NavigateToPose: actions/NavigateToPose.md
    - ClearEntireCostmap: actions/ClearEntireCostmap.md
    - ClearCostmapExceptRegion: actions/ClearCostmapExceptRegion.md
    - ClearCostmapAroundRobot: actions/ClearCostmapAroundRobot.md
    - ClearCostmapAroundPose: actions/ClearCostmapAroundPose.md
    - ReinitializeGlobalLocalization: actions/ReinitializeGlobalLocalization.md
    - TruncatePath: actions/TruncatePath.md
    - TruncatePathLocal: actions/TruncatePathLocal.md
    - PlannerSelector: actions/PlannerSelector.md
    - ControllerSelector: actions/ControllerSelector.md
    - SmootherSelector: actions/SmootherSelector.md
    - GoalCheckerSelector: actions/GoalCheckerSelector.md
    - ProgressCheckerSelector: actions/ProgressCheckerSelector.md
    - NavigateThroughPoses: actions/NavigateThroughPoses.md
    - ComputePathThroughPoses: actions/ComputePathThroughPoses.md
    - RemovePassedGoals: actions/RemovePassedGoals.md
    - CancelControl: actions/CancelControl.md
    - CancelBackUp: actions/CancelBackUp.md
    - CancelSpin: actions/CancelSpin.md
    - CancelWait: actions/CancelWait.md
    - CancelDriveOnHeading: actions/CancelDriveOnHeading.md
    - CancelAssistedTeleop: actions/CancelAssistedTeleop.md
    - CancelComputeAndTrackRoute: actions/CancelComputeAndTrackRoute.md
    - SmoothPath: actions/Smooth.md
    - GetPoseFromPath: actions/GetPoseFromPath.md
    - DockRobot: actions/DockRobot.md
    - UndockRobot: actions/UndockRobot.md
    - ConcatenatePaths: actions/ConcatenatePaths.md
    - GetCurrentPose: actions/GetCurrentPose.md
  - Condition Plugins:
    - GoalReached: conditions/GoalReached.md
    - TransformAvailable: conditions/TransformAvailable.md
    - DistanceTraveled: conditions/DistanceTraveled.md
    - GoalUpdated: conditions/GoalUpdated.md
    - GlobalUpdatedGoal: conditions/GlobalUpdatedGoal.md
    - InitialPoseReceived: conditions/InitialPoseReceived.md
    - IsStuck: conditions/IsStuck.md
    - TimeExpired: conditions/TimeExpired.md
    - IsBatteryLow: conditions/IsBatteryLow.md
    - IsPathValid: conditions/IsPathValid.md
    - PathExpiringTimer: conditions/PathExpiringTimer.md
    - AreErrorCodesPresent: conditions/AreErrorCodesPresent.md
    - WouldAControllerRecoveryHelp: conditions/WouldAControllerRecoveryHelp.md
    - WouldAPlannerRecoveryHelp: conditions/WouldAPlannerRecoveryHelp.md
    - WouldASmootherRecoveryHelp: conditions/WouldASmootherRecoveryHelp.md
    - IsBatteryCharging: conditions/IsBatteryCharging.md
    - ArePosesNear: conditions/ArePosesNear.md
  - Control Plugins:
    - PipelineSequence: controls/PipelineSequence.md
    - RoundRobin: controls/RoundRobin.md
    - RecoveryNode: controls/RecoveryNode.md
  - Decorator Plugins:
    - RateController: decorators/RateController.md
    - DistanceController: decorators/DistanceController.md
    - SpeedController: decorators/SpeedController.md
    - GoalUpdater: decorators/GoalUpdater.md
    - PathLongerOnApproach: decorators/PathLongerOnApproach.md
    - SingleTrigger: decorators/SingleTrigger.md
    - GoalUpdatedController: decorators/GoalUpdatedController.md
