nav:
  - index.md
  - Introduction To Nav2 Specific Nodes: nav2_specific_nodes/nav2_specific_nodes.md
  - Detailed Behavior Tree Walkthrough: detailed_behavior_tree_walkthrough/detailed_behavior_tree_walkthrough.md
  - Navigate To Pose: trees/nav_to_pose_recovery.md
  - Navigate Through Poses: trees/nav_through_poses_recovery.md
  - Navigate To Pose and Pause Near Goal-Obstacle: trees/nav_to_pose_and_pause_near_goal_obstacle/nav_to_pose_and_pause_near_goal_obstacle.md
  - Navigate To Pose With Consistent Replanning And If Path Becomes Invalid: trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.md
  - Navigate on Route Graph with Recovery: trees/navigate_on_route_graph_w_recovery.md
  - Follow Dynamic Point: trees/follow_point.md
  - Odometry Calibration: trees/odometry_calibration/odometry_calibration.md
